package com.example.myapplication.business

data class User(
    val Id: String?,
    val Tokken: String?,
    val NameInitials: String?,
    val Email: String?,
    val FirstName: String?,
    val MiddleName: String?,
    val LastName: String?,
    val Birthday: String?,
    val GenderId: Number?,
    val Phone: String?,
    val AddressLine1: String?,
    val AddressLine2: String?,
    val City: String?,
    val PostCode: String?,
    val CountryId: Number?,
    val CountryName: String?,
    val FullName: String?,
    val DOB: String?,
    val Age: Number?,
    val IsPro: Boolean?,
    val About: String?,
    val ProfileImage: String?,
    val CreatedDateTime: String?,
    val UpdatedDateTime: String?,
    val Roles: String?,
    val IsSuccess: Boolean?,
    val Message: String?,
    val Result: String?
)